sudo: required
dist: trusty

# whitelist
branches:
  only:
    - master

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-5']
#      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7


before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive libicu-dev libxml2-dev libtar-dev libbz2-dev zlib1g-dev xmldiff
    - git clone https://github.com/LanguageMachines/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
    - git clone https://github.com/LanguageMachines/libfolia
    - cd libfolia
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check
