---   # foliatest
sudo: required
dist: bionic
group: edge

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number}-%{branch} : %{message}
        --> %{build_url}"
    skip_join: true

language: cpp
matrix:
  include:
    - os: linux
      cache: ccache
      compiler: g++
      env:
        - SCAN=echo

    - os: linux
      cache: ccache
      compiler: clang++
      env:
        - SCAN=scan-build
        - OPENMPFLAG=--disable-openmp

    - os: osx
      cache: ccache
      compiler: clang
      env:
        - SCAN=echo

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install pkg-config autoconf-archive libicu-dev cppcheck
           libxml2-dev libtar-dev libbz2-dev zlib1g-dev xmldiff;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install pkg-config;
      brew install autoconf-archive;
      brew install xmldiff;
      brew outdated || brew upgrade icu4c;
      brew outdated || brew upgrade libxml2;
      brew outdated || brew install bzip2;
      brew outdated || brew install zlib;
      brew install cppcheck;
      brew install libtar;
      brew install llvm;
      export PATH="/usr/local/opt/llvm/bin:$PATH";
      export LDFLAGS="-L/usr/local/opt/llvm/lib";
      export CXXFLAGS="-I/usr/local/opt/llvm/include";
    fi

  - git clone https://github.com/proycon/foliapy
  - cd foliapy
  - git submodule init && git submodule update   # get folia-repo with examples
  - cd ..

  - git clone https://github.com/LanguageMachines/ticcutils
  - cd ticcutils
  - bash bootstrap.sh
  - ./configure $OPENMPFLAG
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/LanguageMachines/libfolia
  - cd libfolia
  - bash bootstrap.sh
  - ./configure $OPENMPFLAG
  - make
  - sudo make install
  - cd ..
install:
  - bash bootstrap.sh
  - ./configure $OPENMPFLAG
  - cppcheck --enable=all --quiet --error-exitcode=0 .
  - $SCAN --status-bugs make
  - make
  - sudo make install
script:
  - FOLIAPATH=foliapy/folia-repo
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    make check

after_failure:
  - cat src/test-suite.log
