# whitelist
branches:
  only:
    - master

language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive libicu-dev libxml2-dev libtar-dev libbz2-dev zlib1g-dev xmldiff
    - git clone https://github.com/LanguageMachines/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - git clone https://github.com/LanguageMachines/libfolia
    - cd libfolia
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make
    - sudo make install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make check
